title: Dongyub Lee (dongyub63 (at) gmail (dot) com)
url: "https://judelee19.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "CV"
   link: "dongyublee_cv.pdf"

remote_theme: ankitsultana/researcher@gem
